### ISSUE TITLE
Not able to import cdk_ecr_deployment

### ISSUE THREAD

**Issue by geetikatalreja** [cdklabs/cdk-ecr-deployment#100]
I am using python for my CDK project. I want to use this project.
I am not able to import cdk_ecr_deployment
I have also installed "avishayil-cdk.ecr-deployment==0.0.0", but I am getting Module not found error.
from aws_cdk import aws_ecr_assets as ecr_assets, aws_ecr as ecr

```
import os
import enum
#from site_libraries import cdk-ecr-deployment as ecrdeploy
#import cdk_ecr_deployment as ecrdeploy
from avishayil_cdk import ecr_deployment
```
below is the error:
` File "c:\ecr_stack.py", line 7, in <module>
    from avishayil_cdk import ecr_deployment
ModuleNotFoundError: No module named 'avishayil_cdk'`

Please guide how I can use this module.

**Comment by wchaws** [comment]
`cdk-ecr-deployment` hasn't officially release python package yet.

**Comment by geetikatalreja** [comment]
it means I can not use it for aws-cdk python project. if there is any way to use it please let me know. I just want to create ECR repo and upload images in it with image tags.

**Comment by mploski** [comment]
@wchaws  Is there any progress with this topic? I found https://pypi.org/project/avishayil-cdk.ecr-deployment/. Are you involved in this package development as well?

**Comment by wchaws** [comment]
@mploski In short, no. And I'm not involved in https://pypi.org/project/avishayil-cdk.ecr-deployment/

**Comment by eladb** [comment]
@wchaws do you need help publishing to pypi? It should be straightforward. Just add [`publishToPyPi`](https://github.com/projen/projen/blob/main/API.md#projen-jsiipythontarget) setting to your project with the package name and add `TWINE_USERNAME` and `TWINE_PASSWORD` secrets to the repo.

Something like this:

```js
{
  publishToPyPi: {
    distName: 'cdk-ecr-deployment',
    module: 'cdk_ecr_deployment'
  }
}
```

**Comment by wchaws** [comment]
@mploski Python package is published  https://pypi.org/project/cdk-ecr-deployment/#description

**Comment by cu4tro-dgb** [comment]
Is it functional for Python?

<img width="949" height="138" alt="Image" src="https://github.com/user-attachments/assets/e9922114-91d2-4c32-8f8a-ad08777f1b5c" />

**Comment by mrgrain** [comment]
@cu4tro-dgb Seems like a venv problem. This works for me. Does it for you?

```python
python -c "import cdk_ecr_deployment; print('done')"  
```
