### ISSUE TITLE
Trying to pass / override the ECRDeploymentProps.role, but it fails

### ISSUE THREAD

**Issue by shantgup** [cdklabs/cdk-ecr-deployment#110]
Hello,

I have a user who is trying to pass their own role instead of the default role in the below code snippet using the `ECRDeploymentProps.role` property.

```
const ecrDeploy = new ecrdeploy.ECRDeployment(this, 'ecrDeploy', {
        src: new ecrdeploy.DockerImageName(`<REDACTED>`),
        dest: new ecrdeploy.DockerImageName('<REDACTED>'),
        role: dkrEcrLmdarole.lmdaFunRole
       
      });
``` 

The `dkrEcrLmbdarole` is defined as an IRole, however they get the following compilation error.

```
Type 'import("<REDACTED>/node_modules/@aws-cdk/aws-events/node_modules/@aws-cdk/aws-iam/lib/role").IRole' is not assignable to type 'import("<REDACTED>/node_modules/cdk-ecr-deployment/node_modules/@aws-cdk/aws-iam/lib/role").IRole'.
```

Is there a way to fix this issue?

**Comment by wchaws** [comment]
Which version of cdk do u use? This error is typically due to cdk libraries version mismatch. Please upgrade your cdk libraries to the latest.
