### ISSUE TITLE
Support for CDK v2

### ISSUE THREAD

**Issue by dacacioa** [cdklabs/cdk-ecr-deployment#112]
Hi,

Can it be possible to enable compatibility with CDK v2? Is it in the roadmap?

Thanks for your help and your project! 😉

Regards,

D. Acacio

**Comment by wchaws** [comment]
Thanks for your attention. Let's wait until CDK v2 is finally released.

**Comment by dacacioa** [comment]
Ok thanks!

**Comment by rob3c** [comment]
bump to avoid bot closure

**Comment by ahammond** [comment]
`aws-cdk` seems to be taking it's time cutting v2. More than half the people I know are already using it in production because it's significantly better than v1. Any chance this can happen sooner than later?

**Comment by wchaws** [comment]
The v2 has released.
