### ISSUE TITLE
ECR aws-cdk/assets needs to be able to accept additional permissions during creation

### ISSUE THREAD

**Issue by 101Lizardman** [cdklabs/cdk-ecr-deployment#136]
Hey! 

I am using this package to deploy an image during my pipeline, but the user that I used to setup the project and the user that's running the pipeline are different. I cannot programatically add new permissions to the ECR repo after its creation, so it'd be real swell if I could pass-in some IAM Principals or Users that get added to the permissions on creation.

Thanks :)

**Comment by wchaws** [comment]
@101Lizardman cdk-ecr-deployment support adding credential to push/pull docker images via `creds` parameters.

The format of `creds` is `<user>:<password>`. I think you can try it.

```ts
new DockerImageName(name: string, creds?: string)
```
