### ISSUE TITLE
Volunerable dependencies

### ISSUE THREAD

**Issue by eladb** [cdklabs/cdk-ecr-deployment#140]
<img width="718" alt="Screen Shot 2021-12-02 at 17 22 24" src="https://user-images.githubusercontent.com/598796/144450996-bd0e647a-62d4-4138-b0b4-78e6379cb8be.png">

**Comment by wchaws** [comment]
@eladb  These are belongs to golang dependencies. I need to take some time to figure out how to fix it.

**Comment by wchaws** [comment]
Refers https://github.com/containers/skopeo/commit/37d801c90bcf7b5500c828edc34e4fecd4b8c653
