### ISSUE TITLE
Feature request: JFrog Artifactory as a deployment target

### ISSUE THREAD

**Issue by markusl** [cdklabs/cdk-ecr-deployment#169]
Hi!

We have a requirement for storing all production artifacts in a private artifact repository. Could you confirm and update the README if the construct also works with private artifact repositories and not just with AWS ECR.

Best regards,
Markus

**Comment by wchaws** [comment]
@markusl  cdk-ecr-deployment support adding credential to push/pull docker images via `creds` parameters.

The format of `creds` is `<user>:<password>`. I think you can try it.

```ts
new ecrDeploy.ECRDeployment(this, 'DeployDockerImage', {
  src: new ecrDeploy.DockerImageName(imageUri, creds: '<user>:<password>'),
  dest: new ecrDeploy.DockerImageName(`${repo.repositoryUri}:latest`),
});
```

**Comment by markusl** [comment]
@wchaws thanks for the quick reply. We will try this out. If private registries are supported it would be good to also mention this in the "Features" list in the README

**Comment by Hi-Fi** [comment]
Issue with credentials that way is that those are then put as plain text to template. It would be nice to be able to refer to those from Sercret manager/parameter store.
