### ISSUE TITLE
Bug: precompiled lambda download and lambda build are not working behind enterprise proxy

### ISSUE THREAD

**Issue by Hi-Fi** [cdklabs/cdk-ecr-deployment#170]
There's 2 issues:

With precompiled lambda download download fails with TLS error, probably due to self-signed CA at the proxy:
```
RequestError: Client network socket disconnected before secure TLS connection was established
  console.warn
    Can not get prebuilt lambda: Error: Command failed: /usr/local/share/nvm/versions/node/v14.19.0/bin/node /workspace/cdk-example/cdk/node_modules/cdk-ecr-deployment/lambda/install.js /workspace/cdk-example/cdk/node_modules/cdk-ecr-deployment/lambda/out
    RequestError: Client network socket disconnected before secure TLS connection was established
```

With build it fails to get image from ecr, as all should come from/through internal registry.

**Comment by wchaws** [comment]
@Hi-Fi Currently, it doesn't support download through proxy yet. But to support that wouldn't be too hard. 
The [installation script](https://github.com/cdklabs/cdk-ecr-deployment/blob/c682f9634a0549e9724fbddd2c5ece353a668e0a/lambda/install.js) use ["got"](https://github.com/sindresorhus/got) library to fetch precompiled binary. And the"got" support proxy mode based on https://github.com/sindresorhus/got/blob/HEAD/documentation/tips.md#proxying.

Could you please check if enable proxy can solve your problem? PR is welcomed.
