### ISSUE TITLE
Documentation related to secret usage

### ISSUE THREAD

**Issue by Hi-Fi** [cdklabs/cdk-ecr-deployment#178]
I noticed that #171 was merged, but after looking the changes I'm a bit puzzled how to use those.

According the comments `creds` should be either `username:password`, secret's name or secret's ARN. But what I don't see is, which keys from secret is expected to contain the credentials. Or is it expecting that it's only single secret with plain text containing `username:password`?

I didn't spot any calls to parameter store, so I think current approach is only with either plain text credentials or secret manager ones?

According https://github.com/cdklabs/cdk-ecr-deployment/pull/177/files#diff-9f1b97c7018189c67c21c0a76e3b0d73088612a19247c3c1847d2a88a4bfd84cR40 it seems that it's user responsibility to add the policies, so one new feature might be to automatically add those policies needed in a secure way (not giving rights to everything).

**Comment by wchaws** [comment]
Hi @Hi-Fi, I'm busy these days. I will add documentation later. Your guess is right. You can use both plain text credentials and secret manger arn/key name. It's automatically detected.

```ts
new ecrDeploy.DockerImageName('javacs3/javacs3:latest', 'arn:aws:secretsmanager:us-west-2:00000:secret:secret-name')

// or

new ecrDeploy.DockerImageName('javacs3/javacs3:latest', 'secret-name')

// or 

new ecrDeploy.DockerImageName('javacs3/javacs3:latest', 'username:password')
``` 

The format in secret manager is plain text, not JSON.

<img width="427" alt="image" src="https://user-images.githubusercontent.com/68052927/157041785-a216e7d6-293a-4286-9065-ab05b0134359.png">

**Comment by Hi-Fi** [comment]
OK, then I guessed right for my test, thank you. 

I have used to use JSON/key-value secrets, I can create another feature request to fullfill that. I think that should be enough, as it's not encourageable to use parameter store for secrets.
