### ISSUE TITLE
Proxy Usage for lambda install

### ISSUE THREAD

**Issue by NiklasLehnfeld** [cdklabs/cdk-ecr-deployment#180]
How to correctly use Proxy settings for `install.js` file? 

I can see when trying to download the newest version in the `install.js` it uses the `process.env.HTTPS_PROXY`environment:
```
async function download(url, dest) {
  const agent = {};
  agent.https = process.env.HTTPS_PROXY ? new HttpsProxyAgent({proxy: process.env.HTTPS_PROXY}): undefined;
  agent.http = process.env.HTTP_PROXY ? new HttpProxyAgent({proxy: process.env.HTTP_PROXY}): undefined;
  console.log(`download ${url}`);
  await pipeline(
    got.stream(url, { agent }),
    fs.createWriteStream(dest)
  );
}
```

but actually when running the `install.js` in the `index.ts` when instantiating the `ECRDeployment` `child_process.execSync` is used and no environment variables are passed to the properties.
Actual:
```
const installScript = path.join(__dirname, '../lambda/install.js');
const prebuiltPath = path.join(__dirname, '../lambda/out');
child_process.execSync(`${process.argv0} ${installScript} ${prebuiltPath}`);
```

I debugged it locally and a solution would be to simply either pass the own environment variable to `execSync` or the environment variables passed to the constructor of the `ECRDeployment`. But the second choice could be confusing, because they are meant to be for the lambda and not for the cdk code.
So I would suggest sth like: 
```
const installScript = path.join(__dirname, '../lambda/install.js');
const prebuiltPath = path.join(__dirname, '../lambda/out');
child_process.execSync(`${process.argv0} ${installScript} ${prebuiltPath}`, {
   env: process.env
});
```

Or is there any other way I don't see and there is a reason why it is like it is? Then please let me know.
Thanks in advance! :)

**Comment by NiklasLehnfeld** [comment]
Added a pull-request #181 with the possible solution I mentioned in the issue description.

**Comment by wchaws** [comment]
I checked [the doc](https://nodejs.org/docs/latest-v14.x/api/child_process.html#child_process_child_process_execsync_command_options) of `child_process.execSync(command[, options])`. env's default value is `process.env`.

`env` [\<Object\>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object) Environment key-value pairs. Default: process.env.

**Comment by NiklasLehnfeld** [comment]
@wchaws Okay, didn't saw that in the documentation tbh. But that is actually quite weird. When I debug threw the process locally the `process.env` is definitely a different one when being in `getCode` as when being in the `download` function in `install.js`.
I would write a test for it, but it seems that unit testing child processes isn't straight forward.

**Comment by wchaws** [comment]
Which `cdk-ecr-deployment` version do u use?

**Comment by NiklasLehnfeld** [comment]
In my project when I noticed the issue first time I used the newest version `2.4.1`. But when debugging it locally I cloned your repository and wrote a simple test without any expectations which is calling `getCode`:
```
test('child process should use correct environment', () => {
  process.env.HTTPS_PROXY = 'SOME_INVALID_URL';

  getCode('SOME_IMAGE_NAME');
})
```

I was just checking the logs when running the test because of the problem I mentioned above about mocking in child processes. 
When running the test with my changes in `getCode`:
```
child_process.execSync(`${process.argv0} ${installScript} ${prebuiltPath}`, {
    env: process.env,
});
```
It is producing the following logs:

> console.warn
>    Can not get prebuilt lambda: Error: Command failed: node .../cdk-ecr-deployment/lambda/install.js .../cdk-ecr-deployment/lambda/out
>   TypeError [ERR_INVALID_URL]: Invalid URL

Because it is trying to pass the the invalid url in the `HTTPS_PROXY` environment variable to the `HttpsProxyAgent`. 
When running the same test with the original code:
```
child_process.execSync(`${process.argv0} ${installScript} ${prebuiltPath}`);
```
It is producing the following logs:
>console.warn
>    Can not get prebuilt lambda: Error: Command failed: node .../cdk-ecr-deployment/lambda/install.js .../cdk-ecr-deployment/lambda/out
>    HTTPError: Response code 404 (Not Found)

Because it is not trying to pass anything to an `HttpsProxyAgent`, since the `HTTPS_PROXY` env variable is not set and trying to execute the download without any proxy.

It's weird. As you said - the `env` argument should have the `process.env` as a default value.
Is there anything obvious I'm missing?

**Comment by wchaws** [comment]
Is the pre-built lambda url correct?

https://github.com/cdklabs/cdk-ecr-deployment/blob/aa92eebe25594fdfae50ececc33631483ab5dd21/lambda/install.js#L35

**Comment by NiklasLehnfeld** [comment]
I think you misunderstood. The problem isn't that it is not downloading. The problem it should fail in both cases with the error message:
> TypeError [ERR_INVALID_URL]: Invalid URL
Should fail here:
https://github.com/cdklabs/cdk-ecr-deployment/blob/aa92eebe25594fdfae50ececc33631483ab5dd21/lambda/install.js#L33

Because in both cases it **should** have the HTTPS_PROXY field in the environment variables set and it **should** try to pass it to the HttpsProxyAgent class and throw the above error. 

But actually it doesn't throw the error in your current implementation of the getCode function. Means the HTTPS_PROXY field is not set in the environment variables.
