### ISSUE TITLE
Copying from Github to AWS ECR - seems not to work?

### ISSUE THREAD

**Issue by a-h** [cdklabs/cdk-ecr-deployment#190]
I'm testing out copying from Github's `ghcr.io` to AWS ECR.

I am able to copy using the CLI (see example script).

```sh
#!/bin/bash

if [ "${REPO_OWNER}" = "" ]
then
	echo "Missing REPO_OWNER"
	exit 1
fi
if [ "${REPO_NAME}" = "" ]
then
	echo "Missing REPO_NAME"
	exit 1
fi
if [ "${VERSION}" = "" ]
then
	echo "Missing VERSION"
	exit 1
fi
if [ "${AWS_SESSION_TOKEN}" = "" ]
then
	echo "Missing AWS_SESSION_TOKEN - is a role logged in?"
	exit 1
fi

echo REPO_OWNER=${REPO_OWNER} 
echo REPO_NAME=${REPO_NAME} 
echo VERSION=${VERSION} 

export AWS_ACCOUNT_ID=`aws sts get-caller-identity --query "Account" --output text`
export DOCKER_SRC=ghcr.io/${REPO_OWNER}/${REPO_NAME}:${VERSION}
export ECR=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
export DOCKER_TGT=${ECR}/${REPO_NAME}:${VERSION}

echo "Copying from" ${DOCKER_SRC} "to" ${DOCKER_TGT}

docker pull ${DOCKER_SRC}
docker tag ${DOCKER_SRC} ${DOCKER_TGT}
aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR}
docker push ${DOCKER_TGT}
```

However, the CDK version I put together returns "Invalid PhysicalResourceId"

```ts
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as iam from 'aws-cdk-lib/aws-iam';
import * as ecr from 'aws-cdk-lib/aws-ecr';
import * as ecrdeploy from 'cdk-ecr-deployment';

export interface ReleaseTestStackProps extends StackProps {
        // Name of the repository owner, typically the organisation.
        repoOwner: string,
        // Name of the repository storing the Docker image.
        repoName: string,
        // Version number of the app to deploy, e.g. v1.0.1
        version: string,
}

export class ReleaseTestStack extends Stack {
        constructor(scope: Construct, id: string, props: ReleaseTestStackProps) {
                super(scope, id, props);

                if (!props.env || !props.env.region || !props.env.account) {
                        throw new Error("Invalid environment")
                }
                console.log("accountId:", props.env.account);
                console.log("region:", props.env.region);

                const permissionsBoundary = iam.ManagedPolicy.fromManagedPolicyName(this, 'permissionsBoundary', 'ci-permissions-boundary')
                iam.PermissionsBoundary.of(this).apply(permissionsBoundary);

                // Create an ECR repository.
                const repositoryName = "release-test";
                new ecr.Repository(this, "ecr", {
                        repositoryName,
                        imageScanOnPush: true,
                });

                // Copy from the Github source into ECR.
                const src = `ghcr.io/${props.repoOwner}/${props.repoName}:${props.version}`;
                const dest = `${props.env.account}.dkr.ecr.${props.env.region}.amazonaws.com/${repositoryName}:${props.version}`;
                console.log(`Copying from ${src} to ${dest}`);

                new ecrdeploy.ECRDeployment(this, 'copyFromGithubToECR', {
                        src: new ecrdeploy.DockerImageName(src),
                        dest: new ecrdeploy.DockerImageName(dest),
                });
        }
}
```

It outputs the expected names of the repos:

```
accountId: xxxxxxxxx
region: eu-west-1                                                                                                                      
Copying from ghcr.io/a-h/release-test:v1.0.37 to xxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/release-test/nginx:latest
Try to get prebuilt lambda         
```

But then fails:

```
17:45:42 | CREATE_FAILED        | Custom::CDKBucketDeployment | copyFromGithubToEC...omResource/Default
Invalid PhysicalResourceId
17:45:43 | UPDATE_ROLLBACK_IN_P | AWS::CloudFormation::Stack  | ReleaseTestStack
The following resource(s) failed to create: [copyFromGithubToECRCustomResourceECADA172].
17:46:01 | UPDATE_ROLLBACK_COMP | AWS::CloudFormation::Stack  | ReleaseTestStack
17:45:42 | CREATE_FAILED        | Custom::CDKBucketDeployment | copyFromGithubToEC...omResourceECADA172
Invalid PhysicalResourceId


 ❌  ReleaseTestStack failed: Error: The stack named ReleaseTestStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Invalid PhysicalResourceId
    at prepareAndExecuteChangeSet (/Users/adrian/.npm/lib/node_modules/aws-cdk/lib/api/deploy-stack.ts:382:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at CdkToolkit.deploy (/Users/adrian/.npm/lib/node_modules/aws-cdk/lib/cdk-toolkit.ts:209:24)
    at initCommandLine (/Users/adrian/.npm/lib/node_modules/aws-cdk/lib/cli.ts:341:12)

The stack named ReleaseTestStack failed to deploy: UPDATE_ROLLBACK_COMPLETE: Invalid PhysicalResourceId
```

I looked at the CloudFormation behind it, and saw this:

```
  "copyFromGithubToECRCustomResourceECADA172": {
   "Type": "Custom::CDKBucketDeployment",
   "Properties": {
    "ServiceToken": {
     "Fn::GetAtt": [
      "CustomCDKECRDeploymentbd07c930edb94112a20f03f096f53666512MiB28EAD8E4",
      "Arn"
     ]
    },
    "SrcImage": "docker://ghcr.io/a-h/release-test:v1.0.37",
    "DestImage": "docker://xxxxxxxxxx.dkr.ecr.eu-west-1.amazonaws.com/release-test:v1.0.37"
   },
   "UpdateReplacePolicy": "Delete",
   "DeletionPolicy": "Delete",
   "Metadata": {
    "aws:cdk:path": "ReleaseTestStack/copyFromGithubToECR/CustomResource/Default"
   }
  },
```

So I tried using this instead, to strip the `docker:` from the front of the src image.

```
                new ecrdeploy.ECRDeployment(this, 'copyFromGithubToECR', {
                        src: { uri: src },
                        dest: { uri: dest }
                });
```

But that just resulted in being able to deploy the ECR deployment Lambda function, which then logs errors in CloudWatch:

```
fork/exec /var/task/main: permission denied: PathError
null
```

Any pointers?

**Comment by wchaws** [comment]
AFAIK, you must login into `ghcr.io` before you can pull any image. I guess this is the root cause. You could verify this by disable cdk rollback and check the ECR deployment Lambda function's log.

The leading `docker://` is correct. Don't remove that. Check this https://github.com/containers/skopeo for details.

**Comment by a-h** [comment]
Thanks. Those pointers got me up and running.

For some reason, I didn't realise that this tool runs the copy operation from the Lambda function, rather than on the machine where CDK runs (like how `DockerImageAsset` works). Your comment, and link to #178 made me understand that the copy runs inside Lambda, so it now makes sense to me that Lambda wouldn't be logged in to `ghcr.io`, even though the machine running CDK is.

Once I knew this, I added a secret in the format described in #178.

Setting `--no-rollback` as you suggested enabled me to see error logs in the Lambda CloudWatch Logs, instead of just getting `Invalid PhysicalResourceId` from CloudFormation. I have no idea if it's possible to improve the error message there, but that would certainly have been appreciated by me. :)

Once I'd added a secret, I could also see why the example code in the README customises the policy, because the Lambda function didn't have access to that secret. On my first time using a secret, I assumed that the tool would automatically customise the Lambda role to provide access to it. Possibility for an enhancement there I think.

If the tool is/was able to copy locally to ECR instead of running a Lambda in AWS, it would be more efficient for my use case, which is that I've just built a Docker image in Github Actions, and I want to deploy it to an AWS account (testing/staging/production).

With Github's pricing - https://github.com/features/packages#pricing - there's no bandwidth charge for me to push images to AWS, but there is to pull from AWS, so I'd rather do that.

If it was possible to run the copy locally, I could drop AWS having any access to Github. Running the deploy inside a Lambda means that I have to give AWS a Github Access Token to read Docker images, _and_ give Github access to a role in AWS to execute the CDK deploy.

FWIW, the Skopeo docs weren't very enlightening to me (I did read them before) because I'd only really be guessing at whether Github and ECR `implement... "Docker Registry HTTP API V2".` and also, those docs are for Skopeo, so I don't think the parameter in the CDK _should_ have it?

Anyway, in case it helps anyone else, my code now looks like:

```typescript
const src = `ghcr.io/${props.repoOwner}/${props.repoName}:${props.version}`;
const dest = `${props.env.account}.dkr.ecr.${props.env.region}.amazonaws.com/${repositoryName}:${props.version}`;
console.log(`Copying from ${src} to ${dest} using source secret ${props.githubTokenSecretArn}`);

 const deployment = new ecrdeploy.ECRDeployment(this, 'copyFromGithubToECR', {
   src: new ecrdeploy.DockerImageName(src, props.githubTokenSecretArn),
   dest: new ecrdeploy.DockerImageName(dest),
 })
 deployment.addToPrincipalPolicy(new iam.PolicyStatement({
   effect: iam.Effect.ALLOW,
   actions: [
    'secretsmanager:GetSecretValue',
   ],
  resources: [props.githubTokenSecretArn],
}));
```

Thanks again!

**Comment by dancoates** [comment]
Just in case anyone else finds this issue by searching for `Invalid PhysicalResourceId` I was getting the same error but for me it was just because I had the incorrect region in my destination string. So if you're getting this error, double check your `src` and `dest` params that are passed to `ECRDeployment`

**Comment by pepastach** [comment]
Thanks everyone in this thread for detailed comments. It helped me a lot.
I just want to confirm that you'll get `Invalid PhysicalResourceId` error in many cases and the message is not helpful at all. 

**The fastest way to debug is either pass the `--no-rollback` option to `cdk deploy` command, or add `"rollback": false` to your `cdk.json`. This will keep the custom resource lambda deployed and you can check its logs.**

In my case it was permission boundary missing `ecr:BatchGetImage` action.
