### ISSUE TITLE
The deployment always build from the scratch when using in github actions

### ISSUE THREAD

**Issue by duminda-randomforest** [cdklabs/cdk-ecr-deployment#193]
The deployment always build from the scratch when using in github actions which take more time in CICD pipeline. I have provided the necessary env variables to use a prebuilt version. Much appreciated if you could help me to use the prebuilt .

**Comment by wchaws** [comment]
1. What necessary env variables did u add?
2. Which cdk-ecr-deployment version did u use? Is it the latest version?

**Comment by duminda-randomforest** [comment]
No its the version1.0 . the env variables are listed below.

      env:
          NO_PREBUILT_LAMBDA: false
          CI: false

**Comment by wchaws** [comment]
@duminda-randomforest I'm sorry version 1.0 is under maintenance mode, and new features won't be add to v1.x if there's strong needed. Besides that, cdk v1.x will enter maintenance after June 1st https://github.com/aws/aws-cdk/issues/19836. I'd like to advice to upgrade cdk to v2.x and cdk-ecr-deployment to v2.x as well.
