### ISSUE TITLE
golang lambda is horribly slow

### ISSUE THREAD

**Issue by ahammond** [cdklabs/cdk-ecr-deployment#194]
Yes, even with `FORCE_PREBUILT_LAMBDA=1` set. Is there some reason this isn't just an `aws_lambda_node.NodeJsFunction`?

**Comment by ahammond** [comment]
I did an 
```
export FORCE_PREBUILD_LAMBDA=1
```
in my GH Workflow and... it's still doing a golang build?

**Comment by wchaws** [comment]
which cdk-ecr-deployment version do u use?

**Comment by ahammond** [comment]
@wchaws currently using `2.5.1`. I'll try pulling your latest and see if this resolves things. Thank you for the prompt turnaround!!!

**Comment by ahammond** [comment]
Nice!
<img width="1552" alt="Screen Shot 2022-05-30 at 2 10 48 PM" src="https://user-images.githubusercontent.com/445764/171059885-fc1c7c15-a12f-47a5-aeb8-e7604b9c5133.png">
4 min is a reasonable build time. :)
