### ISSUE TITLE
Rebuilding the image from dockerfile on version 2.5.6

### ISSUE THREAD

**Issue by pneves-ciandt** [cdklabs/cdk-ecr-deployment#217]
I have the following code:

```
const imageArm64 = new DockerImageAsset(this, 'myproject-arm64', {
            directory: './',
            file: 'myproject-arm64.docker',
            platform: Platform.LINUX_ARM64,
            exclude: ['cdk.out'],
            buildArgs: {
                BUILD_VERSION: MajorMinorVersion + '.' + process.env.CODEBUILD_BUILD_NUMBER,
            },
        });

new ecrdeploy.ECRDeployment(this, 'DeployDockerImageArm64', {
            src: new ecrdeploy.DockerImageName(imageArm64.imageUri),
            dest: new ecrdeploy.DockerImageName(`${props.env?.account}.dkr.ecr.${props.env?.region}.amazonaws.com/myproject:arm64-latest`),
        });
```

But when the pipeline builds, it generates two Docker Assets, one from DockerImageAsset which builds successfully and another one from the ECRDeployment which fails to build because it doesn't have the other build details I pass on the DockerImageAsset. As far as I understand, shouldn't the ECRDeployment just deploy the image to the dest repo? Why is it building again? I am using the cdk-ecr-deployment on version 2.5.6 and aws-cdk-lib on version 2.42.1

**Comment by mrgrain** [comment]
Closing since this is v2. If this still is an issue with v3, please open a new issue.
