### ISSUE TITLE
Relationship between this package and cdk-docker-image-deployment

### ISSUE THREAD

**Issue by SamStephens** [cdklabs/cdk-ecr-deployment#225]
It appears from https://github.com/aws/aws-cdk/issues/12597 that [cdk-docker-image-deployment](https://github.com/cdklabs/cdk-docker-image-deployment) is now the CDK blessed way to allow users to publish docker image assets to arbitrary ECR repositories.

As there's significant overlap between that package and this one, what is the plan for these two packages? Especially as, despite the apparent CDK team blessing, cdk-docker-image-deployment does [not appear to work for non-Javascript languages](https://github.com/cdklabs/cdk-docker-image-deployment/issues/58), and in addition has seen no sign of activity for months.

**Comment by mrgrain** [comment]
Both packages solve the same problem in similar but different ways. Both packages need to rely on workarounds to achieve this goal. Depending on specific requirements, one way might suit some users better than the other. The packages will receive input based on product priorities and customer engagement. As of this post, it appears that that `cdk-ecr-deployment` is more relevant to solving user's problems than `cdk-docker-image-deployment` - for one reason or another. Neither of these packages are developed with the same priority as `aws-cdk-lib`. The packages are mostly provided as-is and we don't expect new features being added regularly.

The ultimate goal will be to support this feature in `aws-cdk-lib` however this is more complicated (see https://github.com/aws/aws-cdk/issues/31467).

B
