### ISSUE TITLE
Add Go target

### ISSUE THREAD

**Issue by Butterneck** [cdklabs/cdk-ecr-deployment#231]
It's impossible to build Go bindings for a construct library that depends on this package.

The generated `go.mod` clearly can't report the right location for the missing package
```
module myconstructslibrary

go 1.18

require (
	github.com/aws/jsii-runtime-go v1.81.0
	github.com/aws/aws-cdk-go/awscdk/v2 v2.79.1
	cdkecrdeployment/v2 v2.5.6
	github.com/aws/constructs-go/constructs/v10 v10.2.27
	github.com/cdklabs/awscdk-asset-awscli-go/awscliv1/v2 v2.2.178 // indirect
	github.com/cdklabs/awscdk-asset-kubectl-go/kubectlv20/v2 v2.1.1 // indirect
	github.com/cdklabs/awscdk-asset-node-proxy-agent-go/nodeproxyagentv5/v2 v2.0.149 // indirect
)
```

**Comment by mrgrain** [comment]
probably same as https://github.com/cdklabs/cdk-ecr-deployment/issues/877

**Comment by mrgrain** [comment]
Available here: https://github.com/cdklabs/cdk-ecr-deployment-go

**Comment by gshpychka** [comment]
> Available here: https://github.com/cdklabs/cdk-ecr-deployment-go

@mrgrain 404 for me

**Comment by mrgrain** [comment]
> > Available here: https://github.com/cdklabs/cdk-ecr-deployment-go
> 
> @mrgrain 404 for me

Ah, thanks. It was set to private for whatever reason. Hence why it worked for me. 🤦‍♂️
