### ISSUE TITLE
Unable to specfiy custom SecurityGroups for SingletonFunction

### ISSUE THREAD

**Issue by joker3212** [cdklabs/cdk-ecr-deployment#348]
Unable to supply security groups to the ECRDeployment construct to be used by the SingletonFunction. Currently the singleton function creates a default security group. 

Would like to pass in a predefined security group like this

```  
      ...
      memorySize: memoryLimit,
      vpc: props.vpc,
      vpcSubnets: props.vpcSubnets,
      securityGroups: props.securityGroups,
    });

```

**Comment by Felipe-Gmrs** [comment]
@drduhe Do you know when this feature will be released?
