### ISSUE TITLE
There is no response to issues on this repository

### ISSUE THREAD

**Issue by SamStephens** [cdklabs/cdk-ecr-deployment#380]
Tagging @drduhe because that's the only AWS related account I can see contributing to this repository.

There has been no response to issues against this repository for months, including [what appears to be a vulnerability report](https://github.com/cdklabs/cdk-ecr-deployment/issues/226). Please prioritise responding to them.

Alternatively, if AWS no longer responds to issues on this repository, turn off Issues in the repository settings so we don't waste our time on issues that will never be actioned.

It's disrespectful of our time and the contribution we're trying to make to the ecosystem when we're allowed to put work into issues that will never be actioned.

**Comment by evgenyka** [comment]
@SamStephens - following your feedback, we are going to clarify internally on the maintainers' ownership of the repo and update accordingly. However, open source software allows people to access and use the source code under a specific license, and it's a collaborative effort where contributions are appreciated but not mandatory. I understand your concerns about the unaddressed issues. To help resolve them, you have several options:
1. Contribute through Pull Requests: this enables you to participate actively in the development and make direct contributions to the solution.
2. Fork the Repository: If you prefer to work independently or need a feature/fix urgently, forking the repository and making the changes yourself is always an option.

**Comment by SamStephens** [comment]
@evgenyka I'm afraid your Pull Requests suggestion is a little unrealistic. Why would I be submitting Pull Requests to a repository where even [Vulnerability Reports](https://github.com/cdklabs/cdk-ecr-deployment/issues/226) were not receiving responses?

If I'm not seeing any engagement from maintainers with repository issues at all, I'm not going to expect Pull Requests to receive any responses either, and I'm not going to put time into them.

Now I'm getting responses on this repository, I will push a Pull Request for [the issue I'm concerned about](https://github.com/cdklabs/cdk-ecr-deployment/issues/320) when I have time. But this is a two way street - it's not reasonable to expect developers to contribute time when there is no sign of the maintainers doing anything.

**Comment by fabiozig** [comment]
Maintainers should maintain or at least support the code. To be honest, this and other repositories created by AWS are completely abandoned. Some issues will break this repository and will affect many people, and the maintainers are showing zero interest in it. That's the real problem. If AWS maintains this repository, regardless of being open source, then the maintainers should be active and proactive to those breaking change issues... Even more so, when the root cause of those breaking changes are changes within AWS services.

**Comment by mrgrain** [comment]
We are committed to resolving critical issues. Don't expect any new features added that are not currently supported. It might happen, but I recommend you don't count on it. Issues are still useful for other users to share experiences and possible solutions.
