### ISSUE TITLE
Release 3.0.24 does not include bootstrap and bootstrap.sha256

### ISSUE THREAD

**Issue by SamStephens** [cdklabs/cdk-ecr-deployment#526]
As part of investigating https://github.com/cdklabs/cdk-ecr-deployment/issues/478, I discovered that the assets for [release 3.0.24](https://github.com/cdklabs/cdk-ecr-deployment/releases/tag/v3.0.24) do not include the files `bootstrap` and `bootstrap.sha256`.

This means this release cannot be used without setting the `NO_PREBUILT_LAMBDA` environment variable to force the build to happen locally.

I see [some build actions failing since yesterday](https://github.com/cdklabs/cdk-ecr-deployment/actions/runs/7851155619). It seems likely this is related. I see in the build log warnings about using deprecated Node versions. My suspicion is that the root cause is we're using ancient versions of the Github actions.

As part of considering this task and https://github.com/cdklabs/cdk-ecr-deployment/issues/478, I think we should consider whether the prebuilt Lambda functionality is too complex and brittle, and whether it should just be ripped out entirely. Especially given the support status of this package (or lack there of). Building locally was pretty quick when I did it.

**Comment by fabiozig** [comment]
Seems like the problem was solved and the bootstrap files are now uploaded

**Comment by SamStephens** [comment]
Looks like this may have been resolved by https://github.com/cdklabs/cdk-ecr-deployment/pull/528

@vinayak-kukreja , can you please confirm and resolve this issue.

**Comment by SamStephens** [comment]
As per the new normal, it looks like AWS is completely ignoring the existence of a community around their tools, so I'll resolve this on behalf of @vinayak-kukreja
