### ISSUE TITLE
CDK deployment using outdated lambda go

### ISSUE THREAD

**Issue by sauronalexander** [cdklabs/cdk-ecr-deployment#614]
Hi, I am trying to deploy ECR image using this library. I am seeing this error:

```
The runtime parameter of go1.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (provided.al2023) while creating or updating functions.
```

Using cdk_ecr_deplyment version 2.5.30

Could you help address the issue? Thank you.

**Comment by cameron-dunn-sublime** [comment]
There's a newer version of this package (see releases). Looks like v3 moved off of the Go runtime and `provided.al2023` is now used.
