### ISSUE TITLE
Prebuilt binary?

### ISSUE THREAD

**Issue by cmckni3** [cdklabs/cdk-ecr-deployment#75]
Is it possible to supply a prebuilt binary with the npm package?

Supplying a prebuilt binary would speed up synth and deploy times  especially on CI systems.

Great project btw

**Comment by wchaws** [comment]
That's a good point.

**Comment by cmckni3** [comment]
Reopen?

**Comment by cmckni3** [comment]
any word on this?

**Comment by milesgranger** [comment]
Does it seem none of the referenced PRs have solved this?
I'm using the latest release 2.1.3, and CI always ends up building for ~3-4mins in CI pipelines.

**Comment by wchaws** [comment]
@milesgranger I guess it's caused by your env. please unset `CI` `NO_PREBUILT_LAMBDA` env in your CI pipeline. Otherwise it will build from scratch. https://github.com/cdklabs/cdk-ecr-deployment/blob/c682f9634a0549e9724fbddd2c5ece353a668e0a/src/index.ts#L74-L93

**Comment by milesgranger** [comment]
That was it, thank you. :100:
