### ISSUE TITLE
Type error from newer version of constructs package

### ISSUE THREAD

**Issue by cmckni3** [cdklabs/cdk-ecr-deployment#86]
```
Property 'onValidate' is protected but type 'Construct' is not a class derived from 'Construct'.

new ecrdeploy.ECRDeployment(this, 'DeployDockerImage', {
```

For now, I locked my `constructs` version to `3.3.75` in `package.json`

**Comment by wchaws** [comment]
You mean I need to upgrade my `constructs` version to the latest?

**Comment by cmckni3** [comment]
> You mean I need to upgrade my `constructs` version to the latest?

I think so. I believe a new method was added to the construct class.

**Comment by cmckni3** [comment]
Looks good now. Thanks!
